### ISSUE TITLE
您好，有时候 mp3 后缀  没识别，    变成了  null  

### ISSUE THREAD

**Issue by ccjz286** [chenjunyu19/dl-ncm-playlist#1]
正在下载缺少歌曲...
(1/6) 正在下载 [0 bit/s] Ed Sheeran - Photograph.null
events.js:196
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:16)
Emitted 'error' event on ClientRequest instance at:
    at Socket.socketErrorListener (_http_client.js:420:9)
    at Socket.emit (events.js:219:5)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80
}

**Comment by chenjunyu19** [comment]
其实不是没识别，是没有获取到地址。我看了下，这首歌是要 VIP 才能试听的，你登录 VIP 账号了吗？

**Comment by chenjunyu19** [comment]
<https://github.com/chenjunyu19/dl-ncm-playlist/commit/a91f28ac254b01e574dfbfe2cf7783b7c5c5907f>
